In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_sneh = pd.read_excel('For Statistics.xlsx', sheet_name='DataSnehpana', header=0)
df_basti = pd.read_excel('For Statistics.xlsx', sheet_name='DataBasti', header=0)
df_abhya = pd.read_excel('For Statistics.xlsx', sheet_name='DataAbhyanga', header=0)

In [3]:
sneh_manda = df_sneh[df_sneh['Agni']=='Manda'].describe().T
sneh_tikshna = df_sneh[df_sneh['Agni']=='Tikshna'].describe().T
sneh_visham = df_sneh[df_sneh['Agni']=='Visham'].describe().T

basti_manda = df_basti[df_basti['Agni']=='Manda'].describe().T
basti_tikshna = df_basti[df_basti['Agni']=='Tikshna'].describe().T
basti_visham = df_basti[df_basti['Agni']=='Visham'].describe().T

abhya_manda = df_abhya[df_abhya['Agni']=='Manda'].describe().T
abhya_tikshna = df_abhya[df_abhya['Agni']=='Tikshna'].describe().T
abhya_visham = df_abhya[df_abhya['Agni']=='Visham'].describe().T

In [6]:
sneh_manda.to_excel('H:/DATASETS/Pinky Maushi/Agni/sneh_manda_statistics.xlsx')
sneh_tikshna.to_excel('H:/DATASETS/Pinky Maushi/Agni/sneh_tikshna_statistics.xlsx')
sneh_visham.to_excel('H:/DATASETS/Pinky Maushi/Agni/sneh_visham_statistics.xlsx')

basti_manda.to_excel('H:/DATASETS/Pinky Maushi/Agni/basti_manda_statistics.xlsx')
basti_tikshna.to_excel('H:/DATASETS/Pinky Maushi/Agni/basti_tikshna_statistics.xlsx')
basti_visham.to_excel('H:/DATASETS/Pinky Maushi/Agni/basti_visham_statistics.xlsx')

abhya_manda.to_excel('H:/DATASETS/Pinky Maushi/Agni/abhya_manda_statistics.xlsx')
abhya_tikshna.to_excel('H:/DATASETS/Pinky Maushi/Agni/abhya_tikshna_statistics.xlsx')
abhya_visham.to_excel('H:/DATASETS/Pinky Maushi/Agni/abhya_visham_statistics.xlsx')

## Manda

In [7]:
s_manda = sneh_manda[sneh_manda.index != 'Age']['mean'].to_frame().T
a_manda = abhya_manda[abhya_manda.index != 'Age']['mean'].to_frame().T
b_manda = basti_manda[basti_manda.index != 'Age']['mean'].to_frame().T

frames = [s_manda, a_manda, b_manda]

result_manda = pd.concat(frames)

,Neck_Flexion_Diff,Neck_Extension_Diff,Lateral_Rotation_Right_Diff,Lateral_Rotation_Left_Diff,Lateral_Flexion_Right_Diff,Lateral_Flexion_Left_Diff,MNCV_Diff,SNCV_Diff,Pain_Scale
mean,35.50,29.833333,24.500,25.166667,21.166667,20.333333,7.998333,5.606667,-3.333333
mean,39.75,31.000000,20.875,27.000000,21.875000,21.375000,15.977500,18.653750,-6.250000
mean,40.25,26.750000,21.125,19.250000,15.625000,18.125000,14.560000,20.513750,-6.250000

In [11]:
result_manda.index = ['Snehpana', 'Abhyanga', 'Matrabasti']

result_manda

,Neck_Flexion_Diff,Neck_Extension_Diff,Lateral_Rotation_Right_Diff,Lateral_Rotation_Left_Diff,Lateral_Flexion_Right_Diff,Lateral_Flexion_Left_Diff,MNCV_Diff,SNCV_Diff,Pain_Scale
Snehpana,35.50,29.833333,24.500,25.166667,21.166667,20.333333,7.998333,5.606667,-3.333333
Abhyanga,39.75,31.000000,20.875,27.000000,21.875000,21.375000,15.977500,18.653750,-6.250000
Matrabasti,40.25,26.750000,21.125,19.250000,15.625000,18.125000,14.560000,20.513750,-6.250000

In [12]:
result_manda.to_excel('H:/DATASETS/Pinky Maushi/Agni/result_manda.xlsx')
#result_manda.to_csv('H:/DATASETS/Pinky Maushi/Agni/result_manda.csv')

## Tikshna

In [13]:
s_tikshna = sneh_tikshna[sneh_tikshna.index != 'Age']['mean'].to_frame().T
a_tikshna = abhya_tikshna[abhya_tikshna.index != 'Age']['mean'].to_frame().T
b_tikshna = basti_tikshna[basti_tikshna.index != 'Age']['mean'].to_frame().T

frames = [s_tikshna, a_tikshna, b_tikshna]

result_tikshna = pd.concat(frames)

In [14]:
result_tikshna.index = ['Snehpana', 'Abhyanga', 'Matrabasti']

result_tikshna

,Neck_Flexion_Diff,Neck_Extension_Diff,Lateral_Rotation_Right_Diff,Lateral_Rotation_Left_Diff,Lateral_Flexion_Right_Diff,Lateral_Flexion_Left_Diff,MNCV_Diff,SNCV_Diff,Pain_Scale
Snehpana,36.103448,31.275862,22.034483,23.310345,19.137931,19.655172,7.212069,5.383793,-2.448276
Abhyanga,39.642857,32.607143,22.357143,22.285714,18.500000,19.571429,13.382857,15.131786,-6.214286
Matrabasti,36.482759,33.344828,24.068966,22.655172,19.586207,18.344828,11.454483,21.428276,-6.551724

In [15]:
result_tikshna.to_excel('H:/DATASETS/Pinky Maushi/Agni/result_tikshna.xlsx')
#result_manda.to_csv('H:/DATASETS/Pinky Maushi/Agni/result_manda.csv')

## Visham

In [16]:
s_visham = sneh_visham[sneh_visham.index != 'Age']['mean'].to_frame().T
a_visham = abhya_visham[abhya_visham.index != 'Age']['mean'].to_frame().T
b_visham = basti_visham[basti_visham.index != 'Age']['mean'].to_frame().T

frames = [s_visham, a_visham, b_visham]

result_visham = pd.concat(frames)

In [17]:
result_visham.index = ['Snehpana', 'Abhyanga', 'Matrabasti']

result_visham

,Neck_Flexion_Diff,Neck_Extension_Diff,Lateral_Rotation_Right_Diff,Lateral_Rotation_Left_Diff,Lateral_Flexion_Right_Diff,Lateral_Flexion_Left_Diff,MNCV_Diff,SNCV_Diff,Pain_Scale
Snehpana,33.200000,31.800000,20.00,22.600000,20.600000,18.400000,10.800000,4.40,-3.000000
Abhyanga,39.250000,35.250000,21.75,26.500000,20.000000,17.000000,16.102500,18.57,-6.500000
Matrabasti,37.333333,35.666667,23.00,28.666667,20.333333,16.333333,13.866667,22.10,-6.666667

In [18]:
result_visham.to_excel('H:/DATASETS/Pinky Maushi/Agni/result_visham.xlsx')
#result_manda.to_csv('H:/DATASETS/Pinky Maushi/Agni/result_manda.csv')